In [1]:
import tensorflow as tf

In [3]:
print('TensorFlow version:', tf.__version__)
hello = tf.constant("hello world!")
print(hello.numpy())

TensorFlow version: 2.12.0
b'hello world!'


In [5]:
#factorial calculate
def factorial(n):
    if n==1:
        return 0
    else:
        return n*(n-1)

factorial(10)

90

In [6]:
!conda install numpy

Channels:
 - defaults
Platform: osx-arm64
Solving environment: done

# All requested packages already installed.



In [2]:
import numpy as np

In [8]:
my_list =[12,15,18,21]
array=np.array(my_list)
array

array([12, 15, 18, 21])

In [9]:
type(array)

numpy.ndarray

In [11]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.linspace(20,50,5)

array([20. , 27.5, 35. , 42.5, 50. ])

In [5]:
np.random.randint(20,67)

27

In [6]:
np.random.randint(200,497,(3,3))

array([[311, 425, 436],
       [416, 217, 344],
       [285, 394, 462]])

In [7]:
list=[1,4,3,5,55,2,3,5]
array=np.array(list)
array.reshape(2,4)

array([[ 1,  4,  3,  5],
       [55,  2,  3,  5]])

In [8]:
#Activity 3
arr1=np.arange(0,100).reshape(10,10)
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [4]:
np.random.seed(202)
arr2=np.random.randint(200,1000,35)
arr2

array([863, 260, 660, 385, 463, 558, 286, 329, 248, 932, 342, 347, 977,
       742, 748, 325, 543, 317, 220, 816, 290, 663, 243, 508, 319, 523,
       587, 889, 764, 656, 318, 722, 642, 836, 568])

In [6]:
import pandas as pd
df =pd.read_csv('data.csv',encoding='latin1')
df.head()

ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0        10107               30      95.70                2  2871.00   
1        10121               34      81.35                5  2765.90   
2        10134               41      94.74                2  3884.34   
3        10145               45      83.26                6  3746.70   
4        10159               49     100.00               14  5205.27   

         ORDERDATE   STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
0   2/24/2003 0:00  Shipped       1         2     2003  ...   
1    5/7/2003 0:00  Shipped       2         5     2003  ...   
2    7/1/2003 0:00  Shipped       3         7     2003  ...   
3   8/25/2003 0:00  Shipped       3         8     2003  ...   
4  10/10/2003 0:00  Shipped       4        10     2003  ...   

                    ADDRESSLINE1  ADDRESSLINE2           CITY STATE  \
0        897 Long Airport Avenue           NaN            NYC    NY   
1             59 rue de l'Abbaye           NaN          Reims   NaN   
2  27 rue du Colonel Pierre Avia           NaN          Paris   NaN   
3             78934 Hillside Dr.           NaN       Pasadena    CA   
4                7734 Strong St.           NaN  San Francisco    CA   

  POSTALCODE COUNTRY TERRITORY CONTACTLASTNAME CONTACTFIRSTNAME DEALSIZE  
0      10022     USA       NaN              Yu             Kwai    Small  
1      51100  France      EMEA         Henriot             Paul    Small  
2      75508  France      EMEA        Da Cunha           Daniel   Medium  
3      90003     USA       NaN           Young            Julie   Medium  
4        NaN     USA       NaN           Brown            Julie   Medium  

[5 rows x 25 columns]

In [7]:
arr=df.values
arr

array([[10107, 30, 95.7, ..., 'Yu', 'Kwai', 'Small'],
       [10121, 34, 81.35, ..., 'Henriot', 'Paul', 'Small'],
       [10134, 41, 94.74, ..., 'Da Cunha', 'Daniel', 'Medium'],
       ...,
       [10386, 43, 100.0, ..., 'Freyre', 'Diego', 'Medium'],
       [10397, 34, 62.24, ..., 'Roulet', 'Annette', 'Small'],
       [10414, 47, 65.52, ..., 'Yoshido', 'Juri', 'Medium']], dtype=object)